!!skcc.generate.model.secret.ConfigmapEnvPatchModel
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - env:
        - name: asdf
          valueFrom:
            configMapKeyRef:
              key: aaaa
              name: aaa-configmap
        - name: df
          valueFrom:
            configMapKeyRef:
              key: zzzz
              name: aaa-configmap
        name: app
