apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  amdp.io/app: blue-pp
  amdp.io/profile: eb-istio.prod
configMapGenerator:
- behavior: merge
  files:
  - application-custom.yaml
  name: app-config
images:
- !!skcc.generate.model.kustomize.ImagePatchModel
  name: app
  newName: amdp-registry.skamdp.org/eb-istio/prod/blue-pp
  newTag: 0.1.0
kind: Kustomization
namePrefix: blue-pp-
nameSuffix: -prod
patchesJson6902:
- path: service-patch.yaml
  target:
    kind: Service
    name: app
    version: v1
patchesStrategicMerge:
- container-patch.yaml
- imagepolicy-patch.yaml
- pod-lifecycle-patch.yaml
- probe-patch.yaml
- spec-patch.yaml
- replicas-patch.yaml
- active-profiles-patch.yaml
resources:
- ../common/deployment
