!!skcc.generate.model.service.MicroserviceServicePatchModel
apiVersion: v1
kind: Service
metadata:
  name: blue-pp
  namespace: eb-istio
  labels:
    amdp.io/app: blue-pp
    amdp.io/profile: eb-istio.prod
spec:
  sessionAffinity: None
  selector:
    amdp.io/app: blue-pp
    amdp.io/profile: eb-istio.prod
  ports:
  - !!skcc.generate.model.service.ServicePortModel
    name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
